# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
stages: 
  
  # source stage
  - stage: Source
    jobs:
    - job: 
  
  
  # build stage
  - stage: Build
    jobs:
    - job: Build
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
        displayName: 'dotnet build $(buildConfiguration)'
  
  # test stage
  - stage: Test
    jobs:
    - job: Build
    - job: Run

  # release stage
  - stage: Release
    jobs:
    - job: 

  # deploy stage
  - stage: Deploy
    jobs:
    - job: 
